name: Stargaze Faucet Request

on:
  workflow_dispatch:

jobs:
  request-faucet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode repository
        uses: actions/checkout@v3

      - name: Baca address dari file dan jalankan curl
        run: |
          ADDRESS=$(cat address.txt | tr -d '[:space:]') # Membaca dan membersihkan spasi
          echo "Menggunakan Address: $ADDRESS"
          curl -v "https://faucet.ping.pub/stargaze/send/$ADDRESS"
